name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Инсталиране на Chrome
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y libappindicator3-1 fonts-liberation libnss3 lsb-release xdg-utils libatk-bridge2.0-0
          sudo apt-get install -y google-chrome-stable
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --no-build --verbosity normal
